pub const APP_NAME: &str = "tunsmith";
pub const APP_DISPLAY_NAME: &str = "Tunsmith";
pub const CONFIG_FILE: &str = "tunsmith.json";
pub const DEFAULT_INSTANCE_NAME: &str = "tunsmith";
pub const GENERATED_BY_COMMENT: &str = "# Generated by Tunsmith";
pub const PKI_DIR: &str = "pki";
pub const CA_CERT_FILE: &str = "ca.crt";
pub const CA_KEY_FILE: &str = "ca.key";
pub const SERVER_DIR: &str = "server";
pub const CLIENTS_DIR: &str = "clients";
pub const REMOTES_DIR: &str = "remotes";
pub const DIST_DIR: &str = "dist";
pub const DIST_SERVER_DIR: &str = "server";
pub const DIST_CLIENTS_DIR: &str = "clients";
pub const BUILD_STAMP_FILE: &str = "build.json";
pub const DIALECT_OPENVPN_2_4: &str = "openvpn-2.4";
pub const MIN_OPENVPN_MAJOR: u16 = 2;
pub const MIN_OPENVPN_MINOR: u16 = 4;
pub const OPENVPN_NOT_INSTALLED: &str = "Not installed";
pub const BLOCK_OUTSIDE_DNS: &str = "block-outside-dns";
pub const SETENV_OPT: &str = "setenv opt";

pub const PROJECT_VERSION: &str = "0.1.0";

pub const DEFAULT_VPN_PORT: u16 = 1194;
pub const DEFAULT_PROTOCOL: &str = "udp";
pub const DEFAULT_SUBNET: &str = "10.8.0.0/24";
pub const DEFAULT_DEVICE: &str = "tun";
pub const DEFAULT_CIPHER: &str = "AES-256-GCM";
pub const DEFAULT_AUTH: &str = "SHA384";
pub const DEFAULT_KEEPALIVE: &str = "10 120";
pub const DEFAULT_KEEPALIVE_INTERVAL: u32 = 10;
pub const DEFAULT_KEEPALIVE_TIMEOUT: u32 = 120;
pub const DEFAULT_VERB: u8 = 3;
pub const MUTE_LOG_REPEAT: u8 = 20;
pub const STATUS_LOG_INTERVAL: u8 = 10;
pub const OPEN_VPN_STATUS_LOG_PATH: &str = "/var/log/openvpn/ipp.txt";
pub const OPEN_VPN_STATUS_FILE: &str = "/var/log/openvpn/openvpn-status.log";
pub const MIN_TLS_VERSION_LINE: &str = "tls-version-min 1.2";
pub const TOPOLOGY: &str = "subnet";
pub const LINUX_USER: &str = "nobody";
pub const LINUX_GROUP: &str = "nogroup";
pub const EXPLICIT_EXIT_NOTIFY: u8 = 1;

pub const DEFAULT_CA_VALIDITY_YEARS: u32 = 10;
pub const DEFAULT_SERVER_VALIDITY_YEARS: u32 = 2;
pub const DEFAULT_CLIENT_VALIDITY_YEARS: u32 = 1;
pub const CA_KEY_BITS: usize = 4096;
pub const LEAF_KEY_BITS: usize = 2048;
pub const TLS_CRYPT_KEY_BYTES: usize = 256;
pub const TLS_CRYPT_HEX_LINE_CHARS: usize = 32;
pub const DAYS_PER_YEAR: i64 = 365;
pub const COUNTRY_CODE_LEN: usize = 2;

pub const DEFAULT_SSH_PORT: u16 = 22;
pub const DEFAULT_SSH_USER: &str = "root";
pub const DEFAULT_SSH_KEY_ED25519: &str = ".ssh/id_ed25519";
pub const DEFAULT_SSH_KEY_RSA: &str = ".ssh/id_rsa";
pub const KNOWN_HOSTS_FILE: &str = ".ssh/known_hosts";
pub const REMOTE_OPENVPN_SERVER_DIR: &str = "/etc/openvpn/server";
pub const SYSCTL_CONF: &str = "/etc/sysctl.conf";
pub const JOURNAL_TAIL_LINES: u32 = 20;
pub const REMOTE_FILE_MODE: &str = "600";

pub const DEFAULT_DNS_PRIMARY: &str = "8.8.8.8";
pub const DEFAULT_DNS_SECONDARY: &str = "8.8.4.4";

pub const SERVER_CERT_CN: &str = "server";
pub const SERVER_CONF_NAME: &str = "server.conf";
pub const TLS_CRYPT_FILE: &str = "tls-crypt.key";
pub const SERVER_CERT_FILE: &str = "server.crt";
pub const SERVER_KEY_FILE: &str = "server.key";
pub const CLIENT_CERT_FILE: &str = "client.crt";
pub const CLIENT_KEY_FILE: &str = "client.key";

pub const IPV4_MAX_PREFIX: u32 = 32;
pub const MIN_PORT: u16 = 1;
pub const MAX_PORT: u16 = 65535;

pub fn default_dns() -> Vec<String> {
    vec![
        DEFAULT_DNS_PRIMARY.to_string(),
        DEFAULT_DNS_SECONDARY.to_string(),
    ]
}
